version: '3.9'
services:
  db-container:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: emu_web
      POSTGRES_TZ: Europe/Bucharest
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
  web-container:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
        - "3000:3000"
    depends_on:
      - db-container

networks:
  default:
    name: z80-emu_default