version: '3.9'
services:
  db-container:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --locale-provider=icu --icu-locale=en-US"
      POSTGRES_USER: user # ${DB_USER}
      POSTGRES_PASSWORD: pass # ${DB_PASS}
      POSTGRES_DB: z80emu # ${DB_NAME}
      POSTGRES_TZ: Europe/Bucharest
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
  compiler-service:
    build:
      context: ./ccompiler
      dockerfile: Dockerfile
    ports:
      - "4560:4560"
  web-container:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db-container
      - COMPILER_HOST=compiler-service:4560
      - LEPTOS_SITE_ADDR=0.0.0.0:80
      - PUBLIC_URL=localhost:80
    ports:
        - "80:80"
    depends_on:
      - db-container
      - compiler-service

networks:
  default:
    name: z80-emu_default