version: '3.9'
services:
  db-container:
    image: mirage2032/z80emu-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --locale-provider=icu --icu-locale=en-US"
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_TZ: Europe/Bucharest
    volumes:
      - ./db/data:/var/lib/postgresql/data
  compiler-service:
    image: mirage2032/z80compiler-api
  web-container:
    image: mirage2032/z80emu
    environment:
      DB_HOST: db-container
      COMPILER_HOST: compiler-service:4560
      LEPTOS_SITE_ADDR: ${BIND_URL}
      PUBLIC_URL: ${PUBLIC_URL}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
    ports:
      - "80:80"
    depends_on:
      - db-container
      - compiler-service

networks:
  default:
    name: z80-emu_default