version: '3.9'
services:
  db-container:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_TZ: Europe/Bucharest
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data
  web-container:
    build:
      context: ./web
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=db-container
    ports:
        - "3000:3000"
    depends_on:
      - db-container

networks:
  default:
    name: z80-emu_default