name: Dockerhub Image Update

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Z80 Emulator Web Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/z80emu:latest ./web

      - name: Build Compiler Api Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/z80compiler-api:latest ./ccompiler

      - name: Build Z80 Emulator Database Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/z80emu-db:latest ./db

      - name: Pushing Z80 Emulator Web Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/z80emu:latest

      - name: Pushing Compiler Api Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/z80compiler-api:latest

      - name: Pushing Z80 Emulator Database Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/z80emu-db:latest
